import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import Footer from "@/components/layout/Footer"
import Header from "@/components/layout/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Mos",
  description: "Generated by Dev On Play",
  icons: {
    icon: "/faviconDiscode.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container grid place-items-center px-4 md:mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
