spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mos
    username: sa
    password:
  config:
    import:
      classpath:/spring-project-private/application-secret.yml

springdoc:
  swagger-ui:
    path: /swagger/docs

cors-allow-origin: https://https://k-mos.site
